"""create recordings table

Revision ID: c0418ce059f1
Revises: 0006_courses_and_content
Create Date: 2026-07-27 12:52:59.028334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0418ce059f1'
down_revision: Union[str, Sequence[str], None] = '0006_courses_and_content'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fee_structures_name', 'fee_structures', ['name'], unique=False)
    op.create_index('ix_fee_structures_school_id', 'fee_structures', ['school_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lecture_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['class_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recordings_lecture_id', 'recordings', ['lecture_id'], unique=False)
    op.create_index('ix_recordings_teacher_id', 'recordings', ['teacher_id'], unique=False)
    op.create_table('student_fee_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('fee_structure_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('ix_student_fee_invoices_number', 'student_fee_invoices', ['invoice_number'], unique=False)
    op.create_index('ix_student_fee_invoices_school_id', 'student_fee_invoices', ['school_id'], unique=False)
    op.create_index('ix_student_fee_invoices_status', 'student_fee_invoices', ['status'], unique=False)
    op.create_index('ix_student_fee_invoices_student_id', 'student_fee_invoices', ['student_id'], unique=False)
    op.create_table('fee_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('paid_by', sa.UUID(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'BANK_TRANSFER', 'ONLINE', 'CHECK', name='paymentmethod'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['student_fee_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fee_payments_invoice_id', 'fee_payments', ['invoice_id'], unique=False)
    op.create_index('ix_fee_payments_paid_by', 'fee_payments', ['paid_by'], unique=False)
    op.alter_column('academic_years', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('assignment_submissions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('assignment_submissions', 'status',
               existing_type=postgresql.ENUM('submitted', 'late', 'graded', 'returned', name='submissionstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('assignments', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('assignments', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'closed', name='assignmentstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('attendance', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('attendance', 'status',
               existing_type=postgresql.ENUM('present', 'absent', 'late', 'excused', name='attendancestatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('class_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('class_sessions', 'status',
               existing_type=postgresql.ENUM('scheduled', 'active', 'completed', 'cancelled', name='sessionstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('classes', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('course_enrollments', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('course_subjects', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('courses', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    op.alter_column('document_chunks', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'category',
               existing_type=postgresql.ENUM('general', 'course_material', 'assignment', 'report', 'policy', 'other', name='documentcategory'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kb_articles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kb_articles', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'archived', name='articlestatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kb_articles', 'views',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kb_articles', 'likes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kb_articles', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('info', 'warning', 'success', 'error', 'reminder', 'announcement', name='notificationtype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('parent_student_links', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('parents', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('permissions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_questions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_questions', 'question_type',
               existing_type=postgresql.ENUM('mcq', 'true_false', 'short_answer', 'essay', name='questiontype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_questions', 'marks',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_questions', 'order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quizzes', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quizzes', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quizzes', 'shuffle_questions',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quizzes', 'show_results',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quizzes', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'closed', name='quizstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('role_permissions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('schools', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sections', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('fk_sections_class_teacher_id'), 'sections', type_='foreignkey')
    op.alter_column('students', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subjects', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teachers', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_roles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'school_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to schools.id — constraint added in migration 002.',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.alter_column('users', 'school_id',
               existing_type=sa.UUID(),
               comment='FK to schools.id — constraint added in migration 002.',
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('user_roles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('teachers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('subjects', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('students', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_sections_class_teacher_id'), 'sections', 'teachers', ['class_teacher_id'], ['id'], ondelete='SET NULL')
    op.alter_column('sections', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('schools', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('role_permissions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('quizzes', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'closed', name='quizstatus'),
               server_default=sa.text("'draft'::quizstatus"),
               existing_nullable=False)
    op.alter_column('quizzes', 'show_results',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('quizzes', 'shuffle_questions',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('quizzes', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('quizzes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'marks',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'1'::double precision"),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'question_type',
               existing_type=postgresql.ENUM('mcq', 'true_false', 'short_answer', 'essay', name='questiontype'),
               server_default=sa.text("'mcq'::questiontype"),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('permissions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('parents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('parent_student_links', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('info', 'warning', 'success', 'error', 'reminder', 'announcement', name='notificationtype'),
               server_default=sa.text("'info'::notificationtype"),
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('kb_articles', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('kb_articles', 'likes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('kb_articles', 'views',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('kb_articles', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'archived', name='articlestatus'),
               server_default=sa.text("'draft'::articlestatus"),
               existing_nullable=False)
    op.alter_column('kb_articles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('documents', 'category',
               existing_type=postgresql.ENUM('general', 'course_material', 'assignment', 'report', 'policy', 'other', name='documentcategory'),
               server_default=sa.text("'general'::documentcategory"),
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('document_chunks', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.alter_column('courses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('course_subjects', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('course_enrollments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('classes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('class_sessions', 'status',
               existing_type=postgresql.ENUM('scheduled', 'active', 'completed', 'cancelled', name='sessionstatus'),
               server_default=sa.text("'scheduled'::sessionstatus"),
               existing_nullable=False)
    op.alter_column('class_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('attendance', 'status',
               existing_type=postgresql.ENUM('present', 'absent', 'late', 'excused', name='attendancestatus'),
               server_default=sa.text("'absent'::attendancestatus"),
               existing_nullable=False)
    op.alter_column('attendance', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assignments', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'closed', name='assignmentstatus'),
               server_default=sa.text("'draft'::assignmentstatus"),
               existing_nullable=False)
    op.alter_column('assignments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assignment_submissions', 'status',
               existing_type=postgresql.ENUM('submitted', 'late', 'graded', 'returned', name='submissionstatus'),
               server_default=sa.text("'submitted'::submissionstatus"),
               existing_nullable=False)
    op.alter_column('assignment_submissions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('academic_years', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index('ix_fee_payments_paid_by', table_name='fee_payments')
    op.drop_index('ix_fee_payments_invoice_id', table_name='fee_payments')
    op.drop_table('fee_payments')
    op.drop_index('ix_student_fee_invoices_student_id', table_name='student_fee_invoices')
    op.drop_index('ix_student_fee_invoices_status', table_name='student_fee_invoices')
    op.drop_index('ix_student_fee_invoices_school_id', table_name='student_fee_invoices')
    op.drop_index('ix_student_fee_invoices_number', table_name='student_fee_invoices')
    op.drop_table('student_fee_invoices')
    op.drop_index('ix_recordings_teacher_id', table_name='recordings')
    op.drop_index('ix_recordings_lecture_id', table_name='recordings')
    op.drop_table('recordings')
    op.drop_index('ix_fee_structures_school_id', table_name='fee_structures')
    op.drop_index('ix_fee_structures_name', table_name='fee_structures')
    op.drop_table('fee_structures')
    # ### end Alembic commands ###
